### PR TITLE
Merge 0.13

### PR DESCRIPTION
**Pull request by mcg-web**

### CODE REVIEW

**Comment by murtukov** [comment]
@mcg-web 

In the PR #682 I introduces the `TypeGenerator::GLOBAL_VARS` constant to replace all hard-coded strings `globalVariables` in the whole project.

2 things here have to be done:

1. Replace all hardcoded `globalVariables` everywhere, for example.

    replace this
    ```php
    $arguments['globalVariables']->get('container')->getParameter($paramName) 
    ``` 
    with this
    
    ```php
    use Overblog\GraphQLBundle\Generator\TypeGenerator as Generator;
    
    $arguments[Generator::GLOBAL_VARS]->get('container')->getParameter($paramName) 
    ```

2. There are many places in the **tests** directory, where the `eval()` function is used. It's important, that the variable name is the same, so you need for example change this:

    ```php
    public function testGetUserNoTokenStorage(): void
        {
            $globalVariable = new GlobalVariables(['security' => new Security($this->createMock(CoreSecurity::class))]);
            $globalVariable->get('security');
            $this->assertNull(eval($this->getCompileCode()));
        }
    ```
    with this
    ```php
    public function testGetUserNoTokenStorage(): void
        {
           ${TypeGenerator::GLOBAL_VARS} = new GlobalVariables(['security' => new Security($this->createMock(CoreSecurity::class))]);
           ${TypeGenerator::GLOBAL_VARS}->get('security');
           $this->assertNull(eval($this->getCompileCode()));
        }
```

Please first merge the PR #695, because this 2 PRs will definitely have conflicts.

**Comment by mcg-web** [comment]
done @murtukov !

**Comment by murtukov** [comment]
@mcg-web 

It wasn't really necessary to use `TypeGenerator::GLOBAL_VARS` on the right side with the `$expressionLanguage->evaluate` calls:
```php
${TypeGenerator::GLOBAL_VARS} = new GlobalVariables(['container' => $this->getDIContainerMock(['toto' => $object])]);
$this->expressionLanguage->evaluate($name.'("toto")', [TypeGenerator::GLOBAL_VARS => ${TypeGenerator::GLOBAL_VARS}])
```
because you explicitely pass the variable inside the `evaluate` method. So it could for example be just:
```php
$vars = new GlobalVariables(['container' => $this->getDIContainerMock(['toto' => $object])]);
$this->expressionLanguage->evaluate($name.'("toto")', [TypeGenerator::GLOBAL_VARS => $vars])
```
The variable name only matters when you use the built-in `eval` function, because it takes the variables from outer scope, like in this example:
```php
${Generator::GLOBAL_VARS} = new GlobalVariables(['security' => new Security($this->createMock(CoreSecurity::class))]);
$this->assertNull(eval($this->getCompileCode()));
```

**Comment by mcg-web** [comment]
done!

**Comment by murtukov** [comment]
@mcg-web LGTM

**Pull request merged**
