### PR TITLE
fix/profiler-limit-type

### PR DESCRIPTION
**Pull request by clementvtrd**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documented?   | no
| License       | MIT

I'm getting a Symfony error when opening the GraphQL tab of the Profiler. I found out the limit is now hard typed in `int` and a string is actually sent from the ProfilerController.

## Screenshot

Capture d’écran 2023-04-11 à 14 50 25

### CODE REVIEW

**Review by Vincz — DISMISSED** [review]

**Comment by Vincz** [comment]
Hi @clementvtrd 
The problem is caused by this: https://github.com/symfony/symfony/pull/49657
They changed the type from `string` to `int` in a minor version so we have no choice but to check the Symfony version and call the `find` with a `int` or with a `string`. 😞 
Can you take care of this?

**Comment by clementvtrd** [comment]
Hello, yes sure. Thanks for your comment, I will update it in the afternoon.

**Comment by clementvtrd** [comment]
> Hi @clementvtrd The problem is caused by this: [symfony/symfony#49657](https://github.com/symfony/symfony/pull/49657) They changed the type from `string` to `int` in a minor version so we have no choice but to check the Symfony version and call the `find` with a `int` or with a `string`. 😞 Can you take care of this?

@Vincz I did add a check at runtime, I did not really like it but as you said their is no suitable solutions.

**Review by Vincz — APPROVED** [review]

**Review by mkldevops — APPROVED** [review]

**Comment by Vincz** [comment]
Closed in favor of https://github.com/overblog/GraphQLBundle/pull/1117

**Pull request closed without merging**
