### PR TITLE
fix #543

### LINKED ISSUE #543: Decorators do not merge interfaces
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Given the following schema definition:

```yml
InterfaceA:
  type: interface
  config:
    fields:
      a:
        type: String

InterfaceB:
  type: interface
  config:
    fields:
      b:
        type: String

DecoratorA:
  type: object
  decorator: true
  config:
    interfaces:
      - InterfaceA
    fields:
      a:
        type: String

AandB:
  inherits:
    - DecoratorA
  config:
    implements:
      - InterfaceB
    fields:
      b:
        type: String
```

**Problem**

`AandB` does not implement `InterfaceA`.

**Expected behavior**

`AandB` implements `InterfaceA` and `InterfaceB`

### PR DESCRIPTION
**Pull request by akomm**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documented?   | no
| Fixed tickets | #543

### CODE REVIEW

**Comment by mcg-web** [comment]
Thank you @akomm for taking this one, we can fix it from 0.11 I think, since 0.13 is still in development.

**Comment by akomm** [comment]
okay I will change it

**Comment by akomm** [comment]
Do you want 2 separate PR for 0.11 and 0.12 or should I push directly? Can't test it locally, do not have the appropriate php version and can't run the tests cause some phpunit `setUp` have invalid signature (when it was written it was not deprecated xD)

**Comment by mcg-web** [comment]
You can submit this on 0.11 for php 5.6 , I'll merge it after in 0.12 and master. Thank you.

**Pull request closed without merging**
