### PR TITLE
Sort fields, args and values in generated types

### PR DESCRIPTION
**Pull request by mcg-web**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | no
| Fixed tickets | #561 
| License       | MIT

### CODE REVIEW

**Comment by murtukov** [comment]
@mcg-web @ooflorent 

I definitely disagree, that the fields should be sorted. 
If I declared fields in a certain way, then I expect the generated fields be sorted in the same way. 

Why should they automatically be sorted?

**Comment by ooflorent** [comment]
> This is subjective.

Absolutely. However currently it is impossible to keep them sorted when using decorators.
Maybe the feature could be controlled by flag.

What are your thoughts about it @mcg-web?

**Comment by murtukov** [comment]
@ooflorent It can easily be made optional. I would put it under:

```yaml
overblog_graphql:
    compiler:
        sort_fields: true
```

**Comment by mcg-web** [comment]
I'll add a flag cause it's true that having PK like id first can make thing easier. Further more if your object has a lot of field. But what the best default value for this flag? :thinking:

**Comment by ooflorent** [comment]
It's better to default to `false` to avoid breaking changes if people rely on property order.

**Comment by murtukov** [comment]
This PR is outdated. It should be created again on the new codebase. The newly integrated generator library supports sorting array keys in ASC and DESC orders. Feel free to open an issue @ooflorent

**Pull request closed without merging**
