### PR TITLE
Relay pagination customization

### PR DESCRIPTION
**Pull request by Vincz**
see #412 
Add a way to customize the way the Connection & Edges are built when using the Paginator.

### CODE REVIEW

**Comment by Vincz** [comment]
Hey @mcg-web :)
I could use some help to fix the tests.
One of them is failing : https://travis-ci.org/overblog/GraphQLBundle/jobs/448299742, but the `Internal server error` doesn't help to locate the issue.

Also, when running tests locally, I get this error : 
`Error: Class 'Overblog\GraphQLBundle\Access\__DEFINITIONS__\RootQueryType' not found`
Any idea how to solve this ?

**Comment by Vincz** [comment]
Hey @mcg-web :)

Any update about this failing tests?

**Comment by mcg-web** [comment]
Ok @Vincz, I think error comes from the AccessResolver when dealing with connection. I was too busy to fix it last past days but if you don't get it yourself I'll fix this by Friday. Sorry for my late reply.

**Comment by mcg-web** [comment]
Could you add some BC explanations in [upgrade 0.12 notes](https://github.com/overblog/GraphQLBundle/blob/master/UPGRADE-0.12.md) please, since properties are now accessible only by getters and setters? Thanks again for this PR!

**Comment by Vincz** [comment]
Hey @mcg-web , sorry for the late reply. As requested, I updated the upgrade notes.
Tests are ok too.

**Comment by mcg-web** [comment]
Hey @Vincz Thanks for this contribution! I'll add some deprecation messages when accessing private properties to make migration easier before merging this.

**Pull request merged**
