### PR TITLE
Handle @IsPublic & @Access on @Provider to define default values

### PR DESCRIPTION
**Pull request by Vincz**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | yes
| Fixed tickets | #506 
| License       | MIT

### CODE REVIEW

**Comment by mcg-web** [comment]
Thank @Vincz, we could make this one pass in 0.12 since it security scope. What do you think of this?

**Comment by Vincz** [comment]
> Thank @Vincz, we could make this one pass in 0.12 since it security scope. What do you think of this?

Sorry my friend, not sure what you mean. Do you want to merge it in the 0.12, or skip it for the 0.12 and wait for the 0.13 ?

**Comment by mcg-web** [comment]
it's ok for you to submit this for 0.12 branch?

**Comment by Vincz** [comment]
Ho ok, sorry. Yes, yes, no problem for 0.12 :)

**Comment by mcg-web** [comment]
Not a big deal we will keep it in 0.13, thank you @Vincz :+1:

**Pull request merged**
