### PR TITLE
pass schema name to ExecutorArgumentsEvent

### PR DESCRIPTION
**Pull request by videni**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Fixed tickets | #601
| License       | MIT

### CODE REVIEW

**Comment by murtukov** [comment]
Hi @videni 

Is this PR still relevant? Could you add more information what is this PR about?

**Comment by Vincz** [comment]
I think it still makes a lot of sense to get the schema name in the events for multi schemas people.

**Comment by murtukov** [comment]
@Vincz can you take care of this PR? It hangs here already 9 months.

**Comment by Vincz** [comment]
Done in https://github.com/overblog/GraphQLBundle/pull/713

**Pull request closed without merging**
