### PR TITLE
Relay connection/edge fields builders & related annotations

### PR DESCRIPTION
**Pull request by Vincz**
| Q             | A
| ------------- | ---
| New feature?  | yes
| Tests pass?   | yes
| Documented?   | yes
| License       | MIT

The idea of this PR is to use the new Fields builder to generate the relay connections & edges. 
Relay & Connection are just regular GraphQL type except they have specifics fields on them.
The current way to generate relay connection like that:

```yaml
friendConnection:
    type: relay-connection
    config:
        nodeType: User
        resolveNode: '@=resolver("node", [value])'
        edgeFields:
            friendshipTime:
                type: String
                resolve: "Yesterday"
        connectionFields:
            totalCount:
                type: Int
                resolve: '@=resolver("connection")'
```
From my perspective and my experience with this bundle, this way obfuscates the way it works under the hood. 

The new way is more "declarative" and man only needs to understand the easy concept of Fields builder.

```yaml
FriendsConnection:
    type: object
    config:
        builders:
            - builder: relay-connection
              builderConfig:
                  edgeType: FriendsConnectionEdge

FriendsConnectionEdge:
    type: object
    config:
        builders:
            - builder: relay-edge
              builderConfig:
                  nodeType: Character
```

This PR also add annotations to easily add this builder (see the attached doc about the `@Relay\Connection` and `@Relay\Edge`)

### CODE REVIEW

**Comment by Vincz** [comment]
@mcg-web Hey :)
Can you have a look at this PR and tell me what you think?
Wait a little bit before merging, I still need to confront the features to my existing project.

**Comment by Vincz** [comment]
@mcg-web Btw, how can I avoid to get this error: `Error: Class 'Overblog\GraphQLBundle\Access\__DEFINITIONS__\RootQueryType' not found` when running tests in the bundle ?

**Comment by mcg-web** [comment]
Hi @Vincz, this look awesome , yes this implementation is more verbose but indeed it is easier to understand.

> how can I avoid to get this error: Error: Class 'Overblog\GraphQLBundle\Access\__DEFINITIONS__\RootQueryType' not found when running tests in the bundle ?

this error is display when cache was deleted during tests. Try [overriding namespace](https://github.com/overblog/GraphQLBundle/blob/master/tests/Functional/App/config/access/config.yml#L9) in new test case.

**Comment by Vincz** [comment]
Hey @mcg-web ! I think this PR is ready to be merge in the annotations branch !

**Comment by mcg-web** [comment]
Thank you @Vincz !

**Comment by Vincz** [comment]
@ThisIsAreku You're right ! It's missing :) Do you want to submit a PR ?

**Comment by ThisIsAreku** [comment]
PR submitted as https://github.com/overblog/GraphQLBundle/pull/500 🎉  thanks !

**Pull request merged**
