### PR TITLE
abstract resolver for access control

### PR DESCRIPTION
**Pull request by sylfabre**
Adds `isGranted` and `denyAccessUnlessGranted` to a base resolver class to check access like with Symfony controllers

### CODE REVIEW

**Comment by sylfabre** [comment]
@renatomefi The main idea was to provide a base class to extend from like the AbstractController class in Symfony but I can refactor to make it a Trait with the Container Aware thing and people can decide to have their own base class using the trait.

**Comment by mcg-web** [comment]
A trait (`AcessResolverTrait` just an example) will be more useful indeed no need to use Container Aware just use [autowiring](https://symfony.com/doc/current/service_container/autowiring.html#autowiring-other-methods-e-g-setters) to set your authorization checker.

**Comment by renatomefi** [comment]
I said container aware as an example, indeed please don't use containers! hehe

> A trait (AcessResolverTrait just an example) will be more useful indeed no need to use Container Aware just use autowiring to set your authorization checker.

Perfect :+1:

**Comment by mcg-web** [comment]
Closing this because of inactivity, feel free to continue discussion if this is still needed

**Pull request closed without merging**
