### PR TITLE
Reconfigure Travis-CI

### PR DESCRIPTION
**Pull request by murtukov**
- Drop Travis jobs on PHP versions below 7.4
- Replace Xdebug driver with [PCOV](https://github.com/krakjoe/pcov) for coverage tests

#### Update:
- Update PHP-CS-Fixer to v2.16.4

### CODE REVIEW

**Comment by mavimo** [comment]
@murtukov any reason (related to PCOV) to drop the previous versions of PHP?

**Comment by murtukov** [comment]
@mavimo No, there is no specific reason related to PCOV. It just aims the `master` branch, which is **GraphQLBundle 1.0**. It requires PHP >= 7.4.

**Comment by mavimo** [comment]
@murtukov the php-cs-fixer version we are using at the moment (2.15.3) fail on php7.4, can you bump the required version to [v2.16.4](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.16.4) in our [composer.json](https://github.com/overblog/GraphQLBundle/blob/master/composer.json#L84), this should fix the [travis-ci failure](https://travis-ci.org/github/overblog/GraphQLBundle/jobs/702682038), thx!

**Comment by murtukov** [comment]
@mavimo ok, i changed the version but the travis jobs for php-cs-fixer and phpstan were still failing. I performed cs-fix and fixed the reported errors for static analysis. 

The another problem is, that the local code-quality and the one in travis are generating a little different report, that's why I pushed so many commits, because I coudln't check code-quality locally.

I don't know, how other branches were merged, if they all fail in coding quality, even 0.11.

**Comment by mavimo** [comment]
@murtukov LGTM, I see that this branch need to be rebased on master, to you have time to fix it? PS: can you squash all "test" commits into single, please?

@mcg-web do you want to double check ok we can merge it once rebased?

**Comment by mcg-web** [comment]
@mavimo LGTM ! After squash and rebase we can merge this, thank you @murtukov !

**Comment by murtukov** [comment]
@mavimo @mcg-web 

I squashed the commits and rebased onto master. Any thoughts why it doesn't cover `lib/generator` now?

**Comment by mcg-web** [comment]
Everything seem good in the phpunit config file, this issue comes from pcov dir configuration itself

> When pcov.directory is left unset, PCOV will attempt to find src, lib or, app in the current working directory, in that order; If none are found the current directory will be used, which may waste resources storing coverage information for the test suite.

I don't use PCOV so I can't help you on this one.

**Comment by murtukov** [comment]
@mcg-web I am not sure about `pcov.directory` option. Here is why:

- Before rebase and squash all checks passed.
- I tried to do tests with `pcov.directory` option and it didn't work out for me.
- I tried to perform coverage tests locally and it ignores the `lib/generator` both with **Xdebug** and **PCOV** in branches `master`, `0.13`, `0.12`.
- Local coverage test works as expected in the branch 0.11, again with both Xdebug and PCOV.

I am really confused right now. I will change into different target branches of this PR to see if all checks pass.

**Comment by murtukov** [comment]
@mcg-web You were right, the problem was in the `pcov.directory` option, but there were another nuances, that confused me.

Notes for the future:
- When **PCOV** extension is installed, **Xdebug** as automatically disabled. And even if you try to perform coverage test with Xdebug, it will use pcov driver, until you explicitly disable it with `pcov.enabled=0`
- I was putting the `-d` option in the wrong place in the command. They should stay before `bin/phpunit`
    
    Wrong:
    ```
    bin/phpunit --color=always -v --debug -d pcov.enabled=1 -d pcov.directory=. -d pcov.exclude="/(vendor|tests)/" --coverage-clover=build/logs/clover.xml
    ```
    Right:
    ```
    php -d pcov.enabled=1 -d pcov.directory=. -d pcov.exclude="/(vendor|tests)/" bin/phpunit --color=always -v --debug  --coverage-clover=build/logs/clover.xml
    ```
- The versions of PHPUnit below 8 somehow change behavior of pcov. For example with PHPUnit 7.5 it automatically sets option `pcov.directory=.`, at least it was in my case.

**Comment by mavimo** [comment]
@murtukov LGTM!

PS: thx for all the effort you put on this PR! 💪

**Pull request merged**
