### PR TITLE
Made it possible for totalCount to be a promise

### PR DESCRIPTION
**Pull request by rsolyanik**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | no
| License       | MIT

### CODE REVIEW

**Comment by mcg-web** [comment]
Sorry but all released versions are feature freeze. We only accept bugfix or security fix right now for these branches. Your feature add bc so can't definitely not be accepted.

**Comment by rsolyanik** [comment]
> Sorry but all released versions are feature freeze. We only accept bugfix or security fix right now for these branches. Your feature add bc so can't definitely not be accepted.

@mcg-web this don't break bc, but fixes error `Object of class GraphQL\\Executor\\Promise\\Promise could not be converted to int` when trying load total counts in nested lists via data loaders for such queries as` { customers(first: 1000) { edges { node { id, loyaltyAccounts { totalCount edges { node { .... } } } } } } }
`

**Comment by mcg-web** [comment]
Changing the signature of an interface is a bc. If the fix introduce any bc it can be allowed on this branch maybe it can be fixed a different way?

**Comment by murtukov** [comment]
@mcg-web Well, that's a tricky case. What if fixing a bug requires changing the signature of a function? Should we now just leave bugs only because of it? And is it a new feature anyway? I thinks it was supposed to be able to return promises from the beginning and if doesn't work as supposed, then it's a bug.

**Comment by murtukov** [comment]
@mcg-web Well, that's a tricky case. What if fixing a bug requires changing the signature of a function? Should we now just leave bugs only because of it? And is it a new feature anyway? I thinks it was supposed to be able to return promises from the beginning and if doesn't work as supposed, then it's a bug.

What is a BC break? It's something that makes your code fail. The following signature:
```php
public function getTotalCount()
```
is a superset of:
```php
public function getTotalCount(): ?int
```
How can it possibly make your code fail?

**Comment by mcg-web** [comment]
@murtukov there's 2 methods changed, the getter doesn't effectively break anything but what about the setter ?

**Comment by murtukov** [comment]
@mcg-web the same with the setter, he just removed the type hint. I mean how can it possibly break anything?

**Comment by mcg-web** [comment]
This is a public interface. It scope doesn't stop to the bundle, so yes this interface was implemented by other users since it was introduced to help doing that. Changing a public method of a non internal class or interface is a BC.

**Comment by murtukov** [comment]
@mcg-web Then we return back to the previous questions:

1. Is it a bug? Because the documentation says
> The bundle is totally "promise ready"

   yet it fails to return a promise

2. If yes, then what is more important, fixing the bug or stay BC?

**Comment by mcg-web** [comment]
There is always a way of fixing this without breaking BC (some dedicated getter and setter to deal with promise?) , that what I say higher up. I'm not arguing about fixing this bug but the "how" does not follow the release policies of this bundle. We only allow break BC for security reasons. The contract is while updating a minors or a patch release the bundle should not break anything.

**Pull request closed without merging**
