### PR TITLE
Update YamlParser.php

### PR DESCRIPTION
**Pull request by AlexGural**
More comfortable to use constant in some configs. Especially in enum type

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | no
| License       | MIT

Add possibility to use native constant expression for `.yml`

### CODE REVIEW

**Comment by AlexGural** [comment]
@renatomefi sure no problem

**Comment by Kocal** [comment]
Corresponding issue: #303.

**Comment by renatomefi** [comment]
@AlexGural ping, are you still willing to do this? Thanks again!

**Comment by AlexGural** [comment]
@renatomefi I added a small test. I was confused a little bit because I didn`t find tests for YamlParser and symfony parser has a good coverage.

**Comment by mcg-web** [comment]
Closing this because of inactivity, feel free to continue discussion if this is still needed

**Pull request closed without merging**
