### PR TITLE
Added support of Subscription in MetadataParser

### PR DESCRIPTION
**Pull request by marcinjagielnicki**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    |  no
| Deprecations? | no
| Tests pass?   | yes
| Documented? |  no
| Fixed tickets | 
| License       | MIT

Before this change Root Type: Subscription wasn't correcly recognised during metadata parsing while using PHP Annotations/Attributes

### CODE REVIEW

**Comment by Vincz** [comment]
Hi @marcinjagielnicki !
Just a question to better understand your use case. How would you implement the realtime subscriptions?

**Comment by marcinjagielnicki** [comment]
Hey @Vincz,
I'm already working on a bundle that I can consider as working. It's using mercure protocole as a async communcation channel.

**Comment by Vincz** [comment]
@marcinjagielnicki Ho, really nice. Can't wait to see this! Could definitively use it on a bunch of my projects. 
About your PR, is it everything you need to make your bundle work with this one?

**Comment by marcinjagielnicki** [comment]
@Vincz at this moment yes, if I will need any other changes I will make separated PR

**Pull request merged**
