### PR TITLE
Fix md 01

### PR DESCRIPTION
**Pull request by Inego**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | no
| License       | MIT

Fix some typos and improve phrasing in the MD documents of the "Security" section.

### CODE REVIEW

**Comment by mcg-web** [comment]
Thank you @Inego! But can you please change the target branch from master to lastest stable version 0.11 please?

**Comment by Inego** [comment]
Done, but this's begun to look scary.

**Comment by Inego** [comment]
I'd better make a different PR.

**Comment by Inego** [comment]
IMO it should be stated in the "Contrubution" section what branches to base contributions on.

**Pull request closed without merging**
