### PR TITLE
doc(graphql-schema-language): rewrite and add section for mutations

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | yes
| Fixed tickets | #328
| License       | MIT

Rewrite some parts of [GraphQL Schema Language](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/graphql-schema-language.md) documentation, with more concrete examples.
Also add section for mutations.

The changes are visible [here](https://github.com/Kocal/GraphQLBundle/blob/doc/improve-graphql-schema-language-documentation/Resources/doc/definitions/graphql-schema-language.md).

### CODE REVIEW

**Comment by Kocal** [comment]
🙂 

Also is commit 520e8194a8aef2af30b587e7708c3f2f19a4f682 wanted is this PR?

**Comment by mcg-web** [comment]
I commit here because Travis build fails for this PR but yes i right place in on master. I'm doing the change on master an you rebasing this one please?

**Comment by Kocal** [comment]
Oh okay, yea I will rebase.

**Comment by Kocal** [comment]
@mcg-web Rebased 🙂

**Comment by mcg-web** [comment]
Thanks again @Kocal :+1: !

**Pull request merged**
