### PR TITLE
Fix PropertyAccess issue

### PR DESCRIPTION
**Pull request by murtukov**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

New versions of the `symfony/property-access` throw exception on object properties created dynamically. This fix adds the magic method `__get()` to the `ValidationNode` class, so that `PropertyAccess` could access dynamic properties.

**Update:**
Also drop PHP versions below 7.4 in `.travis.yaml`. Both issues prevent each other from passing checks, so they need to be pushed together.

### CODE REVIEW

**Comment by mcg-web** [comment]
Thank you @murtukov . Can you submit this fix to 0.13 branch ? But we should keep older php versions for 0.13.

**Comment by murtukov** [comment]
@mcg-web https://github.com/overblog/GraphQLBundle/pull/687

**Comment by murtukov** [comment]
@mcg-web 

There are 2 problems with Travis:
-  Coding standards fails with a message `PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.`
-  Coverage test always fails, because it exceeds 50 minutes and aborts. Can you increase the time for 1 hour 20 minutes for now? After we replace Xdebug with PCOV this will be not required.

**Comment by mcg-web** [comment]
Closing this one in favor of #687 we will deal with others issue in separated PR. Thank you @murtukov !

**Comment by mcg-web** [comment]
> Coverage test always fails, because it exceeds 50 minutes and aborts. Can you increase the time for 1 hour 20 minutes for now? After we replace Xdebug with PCOV this will be not required.

I can't reproduce this issues with travis 
* [0.11 build take about 6 min](https://travis-ci.org/github/overblog/GraphQLBundle/jobs/702844942) 
* [0.12 build take about 6 min](https://travis-ci.org/github/overblog/GraphQLBundle/jobs/702846450) 
* [0.13 build take about 9 min](https://travis-ci.org/github/overblog/GraphQLBundle/jobs/702849693) 
* [master build take about 9 min](https://travis-ci.org/github/overblog/GraphQLBundle/jobs/702852939) 

@murtukov can you provide an example please?

**Comment by murtukov** [comment]
@mcg-web this PR runs over 50 minutes whenever I push changes: https://github.com/overblog/GraphQLBundle/pull/682

**Comment by mcg-web** [comment]
The issue may come from the feature itself with xdebug

**Pull request closed without merging**
