### PR TITLE
Debug command depends on interface rather on implementations

### PR DESCRIPTION
**Pull request by piotrkreft**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | no
| Fixed tickets | #901 
| License       | MIT

### CODE REVIEW

**Comment by jdecool** [comment]
Hey @piotrkreft I discover your PR :)

I've just made the same thing in #905 but base on 0.13 because it has introduced an error in one of our projects.
Isn't it interesting to have this fix in the `0.13` branch ?

**Comment by piotrkreft** [comment]
@jdecool you might be right :) I haven't received any feedback from repo maintainers yet though to the issue

**Comment by jdecool** [comment]
Let's wait and see what happens

**Review by mcg-web — APPROVED** [review]

**Comment by mcg-web** [comment]
Thank you @piotrkreft !

**Pull request merged**
