### PR TITLE
Fix type generation for Composite symfony validator with explicit 'constraints' key

### PR DESCRIPTION
**Pull request by bravik**
Fix for https://github.com/overblog/GraphQLBundle/issues/991

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | https://github.com/overblog/GraphQLBundle/issues/991
| License       | MIT

### CODE REVIEW

**Comment by mcg-web** [comment]
Thank you @bravik for the fix ! Can you please add a test covering this case?

**Comment by bravik** [comment]
@mcg-web There are only 3 tests for TypeGenerator at all.. Please, I just don't have enough mental strength to do this, while all this war is going on out here...

**Comment by bravik** [comment]
Updated fix to take into account other options passed to validation constraint

**Comment by mcg-web** [comment]
Ok I can understand ! I will add test later with your example in #991. Thanks again for the fix and the feedback !

**Review by mcg-web — APPROVED** [review]

**Comment by bravik** [comment]
@mcg-web will a patch version be released?

**Comment by mcg-web** [comment]
released in [0.14.3](https://github.com/overblog/GraphQLBundle/releases/tag/v0.14.3)

**Pull request merged**
