### PR TITLE
fix #543

### LINKED ISSUE #543: Decorators do not merge interfaces
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Given the following schema definition:

```yml
InterfaceA:
  type: interface
  config:
    fields:
      a:
        type: String

InterfaceB:
  type: interface
  config:
    fields:
      b:
        type: String

DecoratorA:
  type: object
  decorator: true
  config:
    interfaces:
      - InterfaceA
    fields:
      a:
        type: String

AandB:
  inherits:
    - DecoratorA
  config:
    implements:
      - InterfaceB
    fields:
      b:
        type: String
```

**Problem**

`AandB` does not implement `InterfaceA`.

**Expected behavior**

`AandB` implements `InterfaceA` and `InterfaceB`

### PR DESCRIPTION
**Pull request by akomm**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #543
| License       | MIT

### CODE REVIEW

**Comment by akomm** [comment]
Can not test locally, let CI test ;) worked on dev-master...

**Comment by akomm** [comment]
@mcg-web I have merge 0.11 in 0.12 and 0.12 in master, but since I do not know if you want it done directly here without PR, I leave it that. Please tell me how you like this kind of stuff done in future? I can not always test very old versions locally.

**Comment by akomm** [comment]
appveyor flacky & blocking

**Comment by mcg-web** [comment]
I'll merge this once appveyor will be up again, then I'll merge 0.11 → 0.12 → master.

**Comment by akomm** [comment]
> I'll merge this once appveyor will be up again, then I'll merge 0.11 → 0.12 → master.

Okay, so when you tell from 0.11 you do not also want to merges, you do it yourself? (for future PRs) ^^

**Comment by mcg-web** [comment]
Merging from dev branches to dev branches I prefer do it my self so I can know when to release easier. Thanks again for you help!

**Pull request merged**
