### PR TITLE
Paginator backward method now accepts arguments for its callback

### PR DESCRIPTION
**Pull request by alafon**
Make it possible to pass arguments for the callable used in the `auto` and `backward` function of the `Paginator`.

### CODE REVIEW

**Comment by mcg-web** [comment]
hi @alafon , with this change, is the documentation up to date?

**Comment by alafon** [comment]
@mcg-web actually there was no documentation about the `auto()` or `backward()` so no update is needed. But I'll improve it.

**Comment by mcg-web** [comment]
ok nice, thank you :+1:

**Comment by mcg-web** [comment]
tips: use cli `php-cs-fixer fix .` or add the header to fix ci build...

**Comment by alafon** [comment]
I did but like this `vendor/bin/php-cs-fixer fix --dry-run --diff Tests/Relay/Connection/`...
Didn't know that php-cs-fixer does not use the configuration file when using a target... now I know.

**Comment by alafon** [comment]
Added a small piece of doc with a "silly" example, but it does the job :)

**Comment by mcg-web** [comment]
thank you @alafon for contribution ;)

**Pull request merged**
