### PR TITLE
Test pcov coverage driver

### PR DESCRIPTION
**Pull request by murtukov**
! THIS PR SHOULD NOT BE MERGED !

I created this PR as a test to figure out a better configuration for Travis-CI, as this PR ([Feature/generator](https://github.com/overblog/GraphQLBundle/pull/682)) fails to finish, because it aborts at 50 minutes.

This PR is a copy of this one ([Feature/generator](https://github.com/overblog/GraphQLBundle/pull/682)) but I modified the `.travis.yaml` config file to use [PCOV](https://github.com/krakjoe/pcov) driver insted of Xdebug.

It appears, that PCOV is super fast, it finishes the coverage tests in **45 seconds**, whereas **Xdebug requires ~1 hour** to finish.

**So what do you think? Should we replace Xdebug with PCOV for code coverage tests?**

Some performance comparisons:
- [Speed up PHPUnit Code Coverage Analysis](https://medium.com/@nicocabot/speed-up-phpunit-code-coverage-analysis-4e35345b3dad)
- [How to Speedup Coverage on Travis by 95 %](https://pehapkari.cz/blog/2020/01/06/how-to-speedup-code-coverage-on-travis-by-95-percent)

### CODE REVIEW

**Comment by mavimo** [comment]
@murtukov can change the base branch to the feature/generator PR or make this change starting from master?

PS: looks like a very interesting speed improvement!

**Comment by murtukov** [comment]
@mavimo I can open another PR with 1 commit affecting only `.travis.yaml`.

**Comment by mcg-web** [comment]
This change look good to me but yes we should submit it in a dedicated PR.

**Comment by murtukov** [comment]
Closing this PR in favor of #685

**Pull request closed without merging**
